# Generated by Django 5.2.17 on 2026-09-25 04:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('\\A[A-Z]{2}\\Z', 'Use a two-letter uppercase country code.')])),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='markets_market_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hubs', to='markets.market')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='markets_hub_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('\\A[A-Z]{2}\\Z', 'Use a two-letter uppercase country code.')])),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('approval_reference', models.CharField(blank=True, max_length=500)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_areas', to='markets.market')),
            ],
            options={
                'ordering': ['market__code', 'postal_code', 'effective_from'],
                'abstract': False,
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['market', 'country_code', 'postal_code', 'status'], name='service_area_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'INACTIVE'])), name='service_area_status_valid'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='service_area_effective_range_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), models.Q(('effective_from__isnull', False), models.Q(('approval_reference', ''), _negated=True)), _connector='OR'), name='service_area_active_evidence_required')],
            },
        ),
    ]
