# Generated by Django 5.2.17 on 2026-09-21 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"base_manager_name": "objects", "ordering": ["-occurred_at"]},
        ),
        migrations.AlterModelOptions(
            name="businessconfiguration",
            options={
                "base_manager_name": "objects",
                "ordering": ["namespace", "key", "scope_key", "-version"],
            },
        ),
        migrations.AddField(
            model_name="businessconfiguration",
            name="approval_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_configuration_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessconfiguration",
            name="approval_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="businessconfiguration",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="businessconfiguration",
            name="scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION compliance_reject_audit_mutation()
                RETURNS trigger LANGUAGE plpgsql AS $$
                BEGIN
                    RAISE EXCEPTION 'Audit events are append-only.' USING ERRCODE = '55000';
                END;
                $$;
                CREATE TRIGGER compliance_audit_append_only
                BEFORE UPDATE OR DELETE ON compliance_auditevent
                FOR EACH ROW EXECUTE FUNCTION compliance_reject_audit_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER compliance_audit_append_only ON compliance_auditevent;
                DROP FUNCTION compliance_reject_audit_mutation();
            """,
        ),
    ]
