# Generated by Django 5.2.17 on 2026-09-25 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / not operationally available')], default='DRAFT', max_length=16)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='markets.hub')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['public_id'],
                'abstract': False,
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['hub', 'variant', 'status'], name='inventory_unit_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'DRAFT')), name='inventory_unit_foundation_status_valid')],
            },
        ),
    ]
