# Generated by Django 5.2.17 on 2026-09-25 04:01

import catalog.pricing
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='catalog_category_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='catalog_material_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('size_label', models.CharField(blank=True, max_length=100)),
                ('specification', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['sku'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PriceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft')], default='DRAFT', max_length=20)),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed'), ('WEIGHT_BASED', 'Weight based')], max_length=20)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use an uppercase currency code.')])),
                ('fixed_amount', catalog.pricing.ExactDecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weight_value', catalog.pricing.ExactDecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('weight_unit', models.CharField(blank=True, max_length=40)),
                ('rate_amount', catalog.pricing.ExactDecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('rate_unit', models.CharField(blank=True, max_length=40)),
                ('rate_source_reference', models.CharField(blank=True, max_length=500)),
                ('formula_reference', models.CharField(blank=True, max_length=500)),
                ('charges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_revisions', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['variant', '-revision'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Purity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMING_SOON', 'Coming soon'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purities', to='catalog.material')),
            ],
            options={
                'ordering': ['material__code', 'code'],
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.purity'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='catalog_product_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.UniqueConstraint(fields=('variant', 'revision'), name='price_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='price_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT')), name='price_revision_draft_only'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['FIXED', 'WEIGHT_BASED'])), name='price_revision_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='price_fixed_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('weight_value__isnull', True), ('weight_value__gt', 0), _connector='OR'), name='price_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('rate_amount__isnull', True), ('rate_amount__gte', 0), _connector='OR'), name='price_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'FIXED'), ('fixed_amount__isnull', True), _connector='OR'), name='price_weight_has_no_fixed_amount'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('weight_value__isnull', True), ('weight_unit', '')), models.Q(('weight_value__isnull', False), models.Q(('weight_unit', ''), _negated=True)), _connector='OR'), name='price_weight_has_unit'),
        ),
        migrations.AddConstraint(
            model_name='pricerevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rate_amount__isnull', True), ('rate_unit', '')), models.Q(('rate_amount__isnull', False), models.Q(('rate_unit', ''), _negated=True)), _connector='OR'), name='price_rate_has_unit'),
        ),
        migrations.AddConstraint(
            model_name='purity',
            constraint=models.UniqueConstraint(fields=('material', 'code'), name='purity_material_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='purity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='catalog_purity_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMING_SOON', 'INACTIVE'])), name='catalog_variant_status_valid'),
        ),
    ]
